### ISSUE TITLE
How to make ClipPath works on iOS

### ISSUE THREAD

**Issue by luiguild** [nativescript-community/ui-canvas#25]
### Make sure to check the demo app(s) for sample usage 
done

### Make sure to check the existing issues in this repository 
done 

### Which platform(s) does your issue occur on?
- iOS
- iOS 13/14
- Emulator and Device

### Please, provide the following version numbers that your issue occurs with:
- CLI: 7.0.11
- Cross-platform modules: `"@nativescript/core": "~7.0.0"`
- Runtime(s): `"@nativescript/android": "7.0.1", "@nativescript/ios": "7.0.4"`
- Plugin(s):
```json
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/eslint-parser": "^7.11.5",
    "@babel/eslint-plugin": "^7.11.5",
    "@babel/preset-env": "^7.4.5",
    "@babel/traverse": "^7.4.5",
    "@nativescript/android": "7.0.1",
    "@nativescript/ios": "7.0.4",
    "@nativescript/webpack": "~3.0.0",
    "@vue/cli-plugin-babel": "^3.9.0",
    "@vue/cli-plugin-eslint": "^3.9.0",
    "@vue/cli-service": "^4.1.2",
    "@vue/eslint-config-standard": "^4.0.0",
    "babel-loader": "^8.0.6",
    "eslint": "^5.16.0",
    "eslint-plugin-babel": "^5.3.1",
    "eslint-plugin-vue": "^5.0.0",
    "nativescript-vue-template-compiler": "~2.8.0",
    "node-sass": "^4.7.1",
    "pug": "^2.0.3",
    "pug-plain-loader": "^1.0.0",
    "rimraf": "^2.6.3",
    "sass-loader": "^8.0.1",
    "string-replace-loader": "^2.2.0",
    "typescript": "~3.9.0",
    "vue-loader": "~15.9.3"
  }
```
### Please, tell us how to recreate the issue in as much detail as possible. 
1 - create a CanvasView and invoke @draw event
```pug
Page(
  actionBarHidden="true",
  backgroundColor="red"
)
  CanvasView(
    ref="canvas",
    width="100%",
    height="100%",
    @draw="drawCanvas"
  )
```
### Is there any code involved? 
```javascript
drawCanvas ({ canvas }) {
  const baseWidth = screen.mainScreen.widthDIPs // nativescript/core 'screen' dependency 
  const baseHeight = screen.mainScreen.heightDIPs // nativescript/core 'screen' dependency 
  const halfWidth = baseWidth / 2
  const clipRadius = halfWidth * 0.9
  const clipX = halfWidth
  const clipY = (baseHeight / 10) + clipRadius
  const backgroundColor = 'rgba(0, 0, 0, 0.4)'

  // clipPath
  const clipPath = new Path()

  canvas.save()
  clipPath.addCircle(clipX, clipY, clipRadius, Direction.CCW)
  canvas.clipPath(clipPath, Op.DIFFERENCE)

  const backgroundPaint = new Paint()
  backgroundPaint.setAntiAlias(true)
  backgroundPaint.setColor(new Color(backgroundColor))
  backgroundPaint.setStyle(Style.FILL)
  canvas.drawPaint(backgroundPaint)
  canvas.restore()
}
```

This code result in different renderings in iOS and Android. In Android works perfectly (like always) but in iOS don't (like always)... the entire canvas content disappear, like have's nothing to draw, all others methods are ignored on `drawEvent` without any errors, he just ignore and block all other (canvas) things to draw on screen

![photo_2020-11-07_08-25-22](https://user-images.githubusercontent.com/16566338/98439769-d1340380-20d2-11eb-9473-931a94c6d9c3.jpg)
is not necessary put the iOS screenshot because it's just a red screen, without the `clipPath` and the black background
(sorry for the biggest image, I don't know how to reduce the preview)

(every day I ask to myself why in 2020 we still trying making apps for iOS, holy God)

**Comment by farfromrefug** [comment]
@luiguild use ` Direction.CW` for now it will work. Will have to find why it does not work without

**Comment by luiguild** [comment]
Thanks for your support @farfromrefug. I will test this in Monday and then I coming back to report to you.

**Comment by ronalson** [comment]
Hello @farfromrefug 

(I'm helping @luiguild with this implementation on iOS.)

This is what we have so far:

With this code:

```javascript
      const backgroundPaint = new Paint()
      backgroundPaint.setAntiAlias(true)
      backgroundPaint.setColor(new Color(this.backgroundColor))
      backgroundPaint.setStyle(Style.FILL)
      canvas.drawPaint(backgroundPaint)

      canvas.save()
```

We get a dark overlay:

<details>
  <summary>Click to see print</summary>
  
  ![Simulator Screen Shot - iPhone 12 mini - 2020-11-09 at 16 50 12](https://user-images.githubusercontent.com/8891651/98589417-02b3f700-22ac-11eb-9ee3-a9480515ce95.png)
</details>

However, when trying to add the `clipPath` we couldn't get the desired output: an dark overlay with circle (see @luiguild's print screen).

```javascript
      const clipPath = new Path()
      clipPath.addCircle(this.clipX, this.clipY, this.clipRadius, Direction.CW)
      canvas.clipPath(clipPath, Op.DIFFERENCE)

      const backgroundPaint = new Paint()
      backgroundPaint.setAntiAlias(true)
      backgroundPaint.setColor(new Color(this.backgroundColor))
      backgroundPaint.setStyle(Style.FILL)
      canvas.drawPaint(backgroundPaint)

      canvas.save()
```

Either the hole overlay is suppressed, when using `CCW`.

<details>
  <summary>Output using `Direction.CCW`</summary>
  
![Simulator Screen Shot - iPhone 12 mini - 2020-11-09 at 16 55 39](https://user-images.githubusercontent.com/8891651/98590003-ed8b9800-22ac-11eb-8c58-51eb5e4138e4.png)
</details>

or - when using `CW` - we get the opposite of what we want

<details>
  <summary>Output using `Direction.CW`</summary>
  
![Simulator Screen Shot - iPhone 12 mini - 2020-11-09 at 16 40 00](https://user-images.githubusercontent.com/8891651/98590029-f67c6980-22ac-11eb-85ec-dad1e2be23fc.png)
</details>

I tried also a combination of all `Op` found [here](https://github.com/nativescript-community/ui-canvas/blob/242bc26f36153d28e6ca8394c9192b297b0d170f/src/canvas.ios.ts#L131), but none of then worked.

```javascriot
export enum Op {
    DIFFERENCE,
    INTERSECT,
    REPLACE,
    REVERSE_DIFFERENCE,
    UNION,
    XOR,
}
```

Any idea of what we are missing?

---

One thing that I would like to add, but I'm not sure if it is related, was that while running the project on iOS, I noticed this conflict warning below and later I found that it is used here https://github.com/nativescript-community/ui-canvas/blob/242bc26f36153d28e6ca8394c9192b297b0d170f/plugin/platforms/ios/src/BezierUtils.m#L695

```
~/.../Build/Intermediates.noindex/ArchiveIntermediates/appnativescriptvue/IntermediateBuildFilesPath/.../Objects-normal/arm64/UIBezierPath+Elements.o conflicts with same method from another category
```

**Comment by farfromrefug** [comment]
@farfromrefug @luiguild please share a repro example of what you want (android) and what s not working (ios).
No be careful Op are not working on iOS for clipPath and i am not sure i can make it work.
clipPath are a bit tricky and should be used only if necessary.
About the warning i dont se the relation with the linked source.

**Comment by luiguild** [comment]
Hi @farfromrefug the example working on Android
 https://github.com/luiguild/nativescript-ui-canvas-test

**Comment by ronalson** [comment]
this is the output running the demo project on both platforms:

iOS Emulator (same on device) | Android - Galaxy Tab 6S

![Screen Shot 2020-11-09 at 7 24 09 PM](https://user-images.githubusercontent.com/8891651/98603711-4b29df80-22c1-11eb-8c72-d997693efae2.png)

**Comment by farfromrefug** [comment]
@ronalson @luiguild basic support implemented in 4.0.33

**Comment by ronalson** [comment]
@farfromrefug just confirming that it's now working properly on iOS.

<details>
  <summary>🖼️  See preview </summary>
  
  ![IMG_0EE4AE351E0B-1](https://user-images.githubusercontent.com/8891651/98702144-d2766200-2358-11eb-9c86-0bcbdb4e4a1f.jpeg)
</details>

thanks very much for the super-fast response.

**Comment by farfromrefug** [comment]
Can we close this ?

**Comment by luiguild** [comment]
Sure! Thanks!

**Comment by luiguild** [comment]
@farfromrefug how to do the same thing but now using `addRoundRect`?

we are trying this:
```
const clipPath = new Path()
clipPath.addRoundRect(new RectF(200, 400, 200, 400), 10, 10, Direction.CW)
canvas.clipPath(clipPath, Op.DIFFERENCE)
```

but nothing happen even in iOS or Android, any idea?

**Comment by luiguild** [comment]
solved using this:
```
const clipPath = new Path()
const rect = createRectF(
    200,
    400,
    200,
    400
)
clipPath.addRoundRect(
    rect,
    10,
    10,
    Direction.CW
)
canvas.clipPath(clipPath, Op.DIFFERENCE)
```

thanks again!

**Comment by farfromrefug** [comment]
@luiguild wait you mean the rectf constructor did not work ?

**Comment by luiguild** [comment]
@farfromrefug yep, you are right, using the constructor I was unable to do the same thing that when I used the `creactRectF` method

**Comment by farfromrefug** [comment]
@luiguild thanks I ll.fix it

**Comment by luiguild** [comment]
@farfromrefug just to track another thing that is not related, but I figure out right now. I get an error when I try use this:

```
canvas.save()
const rect = createRectF(
  100,
  100,
  100,
  100
)

canvas.drawRoundRect(
  rect,
  10,
  10,
  fillPaint
)

canvas.restore()
```

```
Error: java.lang.Exception: Failed resolving method drawRoundRect on class android.graphics.Canvas
```

**Comment by farfromrefug** [comment]
@luiguild ok so first new RectF works. But you did not understand the [arguments](https://developer.android.com/reference/android/graphics/RectF#RectF(float,%20float,%20float,%20float)). You dont pass the width! 
This is the difference with `createRectF`

Now about your error i cant really help without more info. That error means you passed arguments to `drawRoundRect` which are not good and it cant find the method with the arguments you passed. I need to know what you pass in that moment

**Comment by luiguild** [comment]
> ```
> const clipPath = new Path()
> clipPath.addRoundRect(new RectF(200, 400, 200, 400), 10, 10, Direction.CW)
> canvas.clipPath(clipPath, Op.DIFFERENCE)
> ```

@farfromrefug no sir, I pass 4 parameters, `x: 200`, `y: 400`, `width: 200` and `height: 400`, like in the docs say, 4 parameters: `left`, `top`, `right` and `bottom`... Look that's the same values pass to the `createRectF` method. Obviously that's values are symbolic, and I obviously use some variables to fill this values in my app, but the method's contract it's correct...

It's 'the same' case in my second thing about `drawRoundRect`, the contract it's correct too. 4 parameters, RectF, rx, ry and Paint.

If it's not, help me to figure out whats the discrepancy with my code and the official documentation please.

**Comment by luiguild** [comment]
@farfromrefug ok, I get something, if I try using `drawRoundRect` with `rx` and `ry` with values `!== 0`, then I get the error, but if I put 0 for both values, works fine, drawing a full rectangle without rounded corners...

I found something related with this on stackoverflow
https://stackoverflow.com/questions/41605774/drawroundrect-in-android-not-working/45631170
