### ISSUE TITLE
Any idea to how get Canvas content and save this as an image?

### ISSUE THREAD

**Issue by luiguild** [nativescript-community/ui-canvas#29]
https://github.com/nativescript-community/ui-canvas/blob/6e76d7b305938f7638d2071f62306de717465c6b/src/canvas.ios.ts#L1240

I see that the `setBitmap` are not present in iOS, do you have any workaround for this scenario?

Thks!

**Comment by farfromrefug** [comment]
you are trying to save a CanvasView to image ?

**Comment by farfromrefug** [comment]
this should work https://github.com/enchev/nativescript-screenshot

**Comment by luiguild** [comment]
> 
> 
> you are trying to save a CanvasView to image ?

Yep, I drew something in my Canvas and now I want get the image to send them using social share

**Comment by luiguild** [comment]
> 
> 
> this should work https://github.com/enchev/nativescript-screenshot

I'm already looking to this plugin but in fact, I think that it's not I want

**Comment by farfromrefug** [comment]
@luiguild then explain in more details what you want to achieve . maybe with code ?

**Comment by luiguild** [comment]
So, for an example, I have a Canvas in my view, I draw something nice and after that I would "export" that draw to a "jpg"/"png" file. In the Canvas Web API we can do it getting the blob content, it would be a way also...

**Comment by stemyke** [comment]
@luiguild I created an extended class of CanvasView and did something like this in it:

```typescript
getScaledImage(scale: number = 2.5): ImageSource {
        const canvas = new Canvas(Math.round(this.canvasWidth * scale), Math.round(this.canvasHeight * scale));
        const width = canvas.getWidth();
        const height = canvas.getHeight();
        if (isIOS) {
            canvas.scale(1, -1, width / 2, height / 2);
        }
        this.draw(canvas, width / this.getMeasuredWidth(), true);
        const src = new ImageSource();
        src.setNativeSource(canvas.getImage());
        return src;
}
```

I dont do my drawings in an external callback function but I do it in other subclasses with a custom function:

```typescript
protected draw(canvas: Canvas, ratio: number, forImage?: boolean): void {

}
```

**Comment by stemyke** [comment]
@luiguild I forgot to mention these:

```typescript
get canvasWidth(): number {
    return this.getMeasuredWidth() / this.density;
}

get canvasHeight(): number {
    return this.getMeasuredHeight() / this.density;
}
```

**Comment by farfromrefug** [comment]
@stemyke @luiguild sorry to come back late on this.
There is actually already a much simpler way to do this `Canvas.getImage`
You can see an example [here](https://github.com/nativescript-community/ui-canvas/blob/master/demo-vue/app/canvastests.ts#L17) and the image is saved in the phone gallery [here](https://github.com/nativescript-community/ui-canvas/blob/master/demo-vue/app/examples/Complex.vue#L110)

**Comment by stemyke** [comment]
@farfromrefug Yes, but I wanted it to be scaled. I am already using canvas.getImage() in it.

**Comment by farfromrefug** [comment]
@stemyke i think i did it in my example app, right? But glad you got it
