### ISSUE TITLE
CanvasView in Absolute Layout

### ISSUE THREAD

**Issue by agardes** [nativescript-community/ui-canvas#33]
Thanks for this plugin. I'm using it with NativeScript Vue.

I'm trying to use CanvasView inside an Absolute Layout, in order to put element on top of the canvas. Problem is, canvas doesn't appear anymore once inside an absolute layout. Any idea why ?

Thanks !

**Comment by farfromrefug** [comment]
@agardes that s because you need to give it a size.

**Comment by agardes** [comment]
Uhoh, stupid me. Thanks for that quick helping answer @farfromrefug
